[package]
name = "xcp"
description = "xcp is an experimental and incomplete clone of the Unix `cp` command, with some more user-friendly feedback and some performance optimisations. NOTE: See the README for current limitations."
version = "0.10.1"
edition = "2021"

authors = ["Steve Smith <tarkasteve@gmail.com>"]
homepage = "https://github.com/tarka/xcp/"
repository = "https://github.com/tarka/xcp/"
readme = "README.md"

keywords = ["coreutils", "cp", "files", "filesystem"]
categories =["command-line-utilities"]
license = "GPL-3.0-only"

[badges]
circle-ci = { repository = "tarka/xcp" }
travis-ci = { repository = "tarka/xcp" }

[features]
default = ["kernel_copy_file_range"]
kernel_copy_file_range = []

[profile.release]
overflow-checks = true

[dependencies]
anyhow = "1.0.72"
cfg-if = "1.0.0"
clap = { version = "4.3.21", features = ["derive"] }
crossbeam-channel = "0.5.8"
crossbeam-utils = "0.8.16"
glob = "0.3.1"
ignore = "0.4.20"
indicatif = "0.17.6"
libc = "0.2.147"
log = "0.4.19"
num_cpus = "1.16.0"
simplelog = "0.12.1"
thiserror = "1.0.44"
unbytify = "0.2.0"
walkdir = "2.3.3"
xattr = "1.0.1"

[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
rand_xorshift = "0.3.0"
tempfile = "3.7.1"
test-case = "3.1.0"
uuid = { version = "1.4.1", features = ["v4"] }
