[package]
name = "xcp"
description = "xcp is a (partial) clone of the Unix `cp` command with some more user-friendly feedback and some optimisations."
version = "0.9.2"
edition = "2021"

authors = ["Steve Smith <tarkasteve@gmail.com>"]
homepage = "https://github.com/tarka/xcp/"
repository = "https://github.com/tarka/xcp/"
readme = "README.md"

keywords = ["coreutils", "cp", "files", "filesystem"]
categories =["command-line-utilities"]
license = "GPL-3.0-only"

[badges]
circle-ci = { repository = "tarka/xcp" }
travis-ci = { repository = "tarka/xcp" }

[features]
default = ["kernel_copy_file_range"]
kernel_copy_file_range = []

[profile.release]
overflow-checks = true

[dependencies]
anyhow = "1.0.65"
cfg-if = "1.0.0"
crossbeam-channel = "0.5.6"
crossbeam-utils = "0.8.12"
glob = "0.3.0"
ignore = "0.4.18"
indicatif = "0.16.2"
libc = "0.2.134"
log = "0.4.17"
num_cpus = "1.13.1"
simplelog = "0.11.2"
structopt = "0.3.26"
thiserror = "1.0.37"
unbytify = "0.2.0"
walkdir = "2.3.2"
xattr = "0.2.3"

[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
rand_xorshift = "0.3.0"
tempfile = "3.3.0"
test-case = "1.2.3"
uuid = { version = "0.8.2", features = ["v4"] }
