[package]
name = "xcp"
description = "xcp is a (partial) clone of the Unix `cp` command with some more user-friendly feedback and some optimisations."
version = "0.9.1-alpha.0"
edition = "2018"

authors = ["Steve Smith <tarkasteve@gmail.com>"]
homepage = "https://github.com/tarka/xcp/"
repository = "https://github.com/tarka/xcp/"
readme = "README.md"

keywords = ["coreutils", "cp", "files", "filesystem"]
categories =["command-line-utilities"]
license = "GPL-3.0-only"

[badges]
circle-ci = { repository = "tarka/xcp" }
travis-ci = { repository = "tarka/xcp" }

[features]
default = ["kernel_copy_file_range"]
kernel_copy_file_range = []

[profile.release]
overflow-checks = true

[dependencies]
anyhow = "1.0.35"
cfg-if = "1.0.0"
crossbeam-channel = "0.5.0"
crossbeam-utils = "0.8.1"
glob = "0.3.0"
ignore = "0.4.17"
indicatif = "0.15.0"
libc = "0.2.81"
log = "0.4.11"
num_cpus = "1.13.0"
simplelog = "0.8.0"
structopt = "0.3.21"
thiserror = "1.0.22"
unbytify = "0.2.0"
walkdir = "2.3.1"
xattr = "0.2.2"

[dev-dependencies]
rand = "0.7.3"
rand_distr = "0.3.0"
rand_xorshift = "0.2.0"
tempfile = "3.1.0"
test-case = "1.0.0"
uuid = { version = "0.8.1", features = ["v4"] }
