[package]
name = "libfs"
description = "."
version = "0.1.1"
edition = "2021"

authors = ["Steve Smith <tarkasteve@gmail.com>"]
homepage = "https://github.com/tarka/xcp/libfs"
repository = "https://github.com/tarka/xcp/libfs"
readme = "README.md"

keywords = ["coreutils", "cp", "files", "filesystem"]
categories =["filesystem"]
license = "GPL-3.0-only"

[features]
default = ["use_linux"]
use_linux = []

[dependencies]
cfg-if = "1.0.0"
libc = "0.2.150"
linux-raw-sys = { version = "0.6.2", features = ["ioctl"] }
log = "0.4.20"
rustix = { version = "0.38.26", features = ["fs"] }
tempfile = "3.8.1"
thiserror = "1.0.50"
xattr = "1.0.1"
