version: 2
jobs:
  build:
    # Use a recent machine image as we need a kernel >= 4.5
    machine:
      image: cimg/rust:1.36.0
    steps:
      - checkout

      - restore_cache:
          key: rust-cache

      - run:
          name: Run tests
          command: ~/.cargo/bin/cargo test --color never

      - run:
          name: Run expensive tests
          command: ~/.cargo/bin/cargo test --color never -- --ignored --nocapture

      - save_cache:
          key: rust-cache
          paths:
            - ./target/
            - ~/.cargo/
            - ~/.rustup/
