[package]
name = "libxcp"
description = "xcp is an experimental and incomplete clone of the Unix `cp` command. This library is the core functionality, including drivers."
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"

authors = ["Steve Smith <tarkasteve@gmail.com>"]
homepage = "https://github.com/tarka/xcp"
repository = "https://github.com/tarka/xcp"
readme = "README.md"

keywords = ["coreutils", "cp", "files", "filesystem"]
categories =["command-line-utilities"]
license = "GPL-3.0-only"

[features]
default = ["parblock", "use_linux"]
parblock = []
use_linux = ["libfs/use_linux"]
# For CI; disable feature testing on filesystems that don't support
# it. See .github/workflows/tests.yml
test_no_reflink = ["libfs/test_no_reflink"]
test_no_sparse = ["libfs/test_no_sparse"]
test_no_extents = ["libfs/test_no_extents"]
test_no_sockets = ["libfs/test_no_sockets"]
test_no_xattr = []
test_no_symlinks = []
test_no_perms = []
test_run_expensive = []


[dependencies]
anyhow = "1.0.79"
blocking-threadpool = "1.0.1"
cfg-if = "1.0.0"
clap = { version = "4.4.16", features = ["derive"] }
crossbeam-channel = "0.5.11"
glob = "0.3.1"
ignore = "0.4.22"
indicatif = "0.17.7"
libfs = { version = "0.5.1", path = "../libfs" }
log = "0.4.20"
num_cpus = "1.16.0"
thiserror = "1.0.56"
unbytify = "0.2.0"
walkdir = "2.4.0"

[dev-dependencies]
# fslock = "0.2.1"
# rand = "0.8.5"
# rand_distr = "0.4.3"
# rand_xorshift = "0.3.0"
# tempfile = "3.9.0"
# test-case = "3.3.1"
# uuid = { version = "1.6.1", features = ["v4"] }
# xattr = "1.2.0"

[lints.clippy]
upper_case_acronyms = "allow"
