name: BTRFS

on: [push]

jobs:
  btrfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-fs.sh btrfs
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/btrfs/src
        env:
          XCP_TEST_FS: btrfs
