name: Ext2

on: [push]

jobs:
  ext2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-fs.sh ext2
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/ext2/src
        env:
          XCP_TEST_FS: ext2
