name: Ext4

on: [push]

jobs:
  ext4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-fs.sh ext4
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/ext4/src
        env:
          XCP_TEST_FS: ext4
