name: Rust

on: [push]

# f2fs and exfat modules are in linux-modules-extra-azure
# and cannot be installed reliably:
# https://github.com/actions/runner-images/issues/7587

jobs:
  ext2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-filesystems.sh ext2
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/ext2/src
        env:
          XCP_TEST_FS: ext2

  ext4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-filesystems.sh ext4
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/ext4/src
        env:
          XCP_TEST_FS: ext4

  xfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-filesystems.sh xfs
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/xfs/src
        env:
          XCP_TEST_FS: xfs

  btrfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-filesystems.sh btrfs
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/btrfs/src
        env:
          XCP_TEST_FS: btrfs

  ntfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-filesystems.sh ntfs
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/ntfs/src
        env:
          XCP_TEST_FS: ntfs

  fat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-filesystems.sh fat
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/fat/src
        env:
          XCP_TEST_FS: fat

  zfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-filesystems.sh zfs
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/zfs/src
        env:
          XCP_TEST_FS: zfs

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash /dev/stdin -y

      - name: Update Rust (installer may lag behind)
        run: ~/.cargo/bin/rustup update

      - name: Run tests
        run: ~/.cargo/bin/cargo test --no-default-features

      - name: Run expensive tests
        run: ~/.cargo/bin/cargo test --no-default-features -- --ignored
