name: XFS

on: [push]

# f2fs and exfat modules are in linux-modules-extra-azure
# and cannot be installed reliably:
# https://github.com/actions/runner-images/issues/7587

jobs:
  xfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-fs.sh xfs
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/xfs/src
        env:
          XCP_TEST_FS: xfs
