name: ZFS

on: [push]

jobs:
  zfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ~/.cargo/bin/rustup update
      - name: Create filesystem
        run: .github/workflows/make-fs.sh zfs
      - name: Run tests
        run: cargo test && cargo test -- --ignored
        working-directory: /fs/zfs/src
        env:
          XCP_TEST_FS: zfs
